line_length: 145
disabled_rules:
  - todo
excluded:
  - Pods
  - Carthage
included:
  - RxAudioVisual/
  - RxAudioVisualTests/
  - Example/Example/
variable_name:
  excluded:
    - e
    - usesExternalPlaybackWhileExternalScreenIsActive
reporter: "xcode"
